/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_identity_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Le jeton d'accès n'est pas requis : la preuve de possession du refresh token
         *     suffit, et c'est justement quand le JWT vient d'expirer qu'on veut pouvoir
         *     se déconnecter proprement.
         */
        post: operations["post_identity_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_identity_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patch_identity_me_update"];
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_identity_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_identity_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/social/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_identity_social_sign_in"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progression": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_progression_state"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progression/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * L'argument `#[MapQueryString]` n'est ni nullable ni pourvu d'un défaut, et c'est
         *     voulu : le résolveur ne construit le DTO sur une query string vide que dans ce
         *     cas-là. Nullable, il faudrait un `?? new XpHistoryQuery()` à la main.
         */
        get: operations["get_progression_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/titles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_progression_titles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/titles/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["put_progression_titles_select"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/training/sessions/{id}/abandon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_training_session_abandon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/training/sessions/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_training_session_active"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/training/sessions/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_training_session_complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/training/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_training_session_list"];
        put?: never;
        post: operations["post_training_session_start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Une erreur, RFC 9457. `type` est l'identifiant stable de la panne ; `title` et
         *     `detail` sont du texte. Certaines erreurs ajoutent leurs propres membres — une
         *     séance déjà active donne `activeSessionId`, un cooldown donne `remainingSeconds`
         *     et `readyAt` — pour que le client se recale au lieu d'afficher un refus sec.
         */
        ProblemDetails: {
            /**
             * Format: uri
             * @enum {string}
             */
            type: "https://grrind.app/problems/validation-failed" | "https://grrind.app/problems/internal-error" | "https://grrind.app/problems/idempotency-key-required" | "https://grrind.app/problems/idempotency-key-in-flight" | "https://grrind.app/problems/idempotency-key-reused" | "https://grrind.app/problems/email-already-used" | "https://grrind.app/problems/email-belongs-to-another-account" | "https://grrind.app/problems/invalid-refresh-token" | "https://grrind.app/problems/social-sign-in-rejected" | "https://grrind.app/problems/social-profile-incomplete" | "https://grrind.app/problems/session-not-found" | "https://grrind.app/problems/session-not-active" | "https://grrind.app/problems/session-already-active" | "https://grrind.app/problems/session-too-short" | "https://grrind.app/problems/session-cooldown" | "https://grrind.app/problems/title-unknown" | "https://grrind.app/problems/title-not-unlocked";
            /** @example Conflict */
            title: string;
            /** @example 409 */
            status: number;
            detail: string;
        } & {
            [key: string]: unknown;
        };
        /** @description Le corps est bien formé mais son contenu est refusé. Chaque violation nomme son champ. */
        ValidationProblem: components["schemas"]["ProblemDetails"] & {
            violations?: {
                /** @example email */
                field: string;
                message: string;
            }[];
        };
        /**
         * @description **La seule forme d'un titre dans toute l'API** — débloqué comme verrouillé, dans le
         *     profil, sur le mur des titres et dans une récompense. Un seul type à décoder, un
         *     seul composant à dessiner.
         *
         *     `unlockedAt` à `null` est ce qui distingue les deux états. `progress` est toujours
         *     renseignée : sur un titre acquis, `current` vaut `target`.
         */
        PlayerTitle: {
            /** @example first_steps */
            id: string;
            /**
             * @description Déjà traduit, dans la langue négociée sur `Accept-Language`.
             * @example First Steps
             */
            name: string;
            /**
             * @description Ce qu'il reste à faire, rédigé.
             * @example Complete your first session
             */
            hint: string;
            unlocked: boolean;
            /** Format: date-time */
            unlockedAt: string | null;
            progress: {
                /** @description Écrêté à `target` — une barre ne dépasse pas. */
                current: number;
                target: number;
                /** @enum {string} */
                unit: "LEVELS" | "XP" | "SESSIONS" | "SECONDS";
            };
        };
        UserProfile: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            displayName: string;
            /**
             * @description Identifiant IANA. **Le streak et le plafond quotidien se calculent dedans** : c'est un attribut de profil, jamais une déduction.
             * @example Europe/Paris
             */
            timezone: string;
            /** Format: date-time */
            registeredAt: string;
            /** @description Le titre porté, ou `null` si le joueur n'en a débloqué aucun ou n'en affiche aucun. */
            title: components["schemas"]["PlayerTitle"] | null;
            /** @description Le plus proche d'aboutir parmi ceux qui restent. `null` quand il les a tous. */
            nextTitle: components["schemas"]["PlayerTitle"] | null;
        };
        /**
         * @description Deux jetons de nature différente. Le JWT porte l'identité et ne se révoque pas —
         *     d'où sa courte durée. Le refresh token est **à usage unique et rotatif**, groupé par
         *     famille : une famille est un appareil connecté, s'en déconnecter la révoque
         *     entièrement. Rejouer un jeton déjà consommé révoque toute la famille.
         */
        TokenPair: {
            accessToken: string;
            /** @enum {string} */
            tokenType: "Bearer";
            /**
             * @description Secondes de validité du JWT.
             * @example 900
             */
            expiresIn: number;
            refreshToken: string;
            /** Format: date-time */
            refreshTokenExpiresAt: string;
        };
        /** @description Ce que rendent l'inscription, la connexion et le rafraîchissement — le profil et la paire de jetons, en une réponse. */
        AuthSession: {
            user: components["schemas"]["UserProfile"];
            tokens: components["schemas"]["TokenPair"];
        };
        /**
         * @description Une séance, ouverte ou close — **une seule forme**, jamais deux. `endedAt` et
         *     `durationSeconds` valent `null` tant qu'elle court, plutôt que de disparaître : un
         *     champ qui apparaît et disparaît finit lu de travers.
         *
         *     `durationSeconds` est la durée **retenue**, déjà écrêtée au plafond. Ce n'est pas
         *     `endedAt - startedAt` sur une séance trop longue, et c'est elle qui fait foi.
         */
        TrainingSession: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            discipline: "RUNNING" | "CYCLING" | "SWIMMING" | "STRENGTH" | "MOBILITY" | "CLIMBING";
            /** @enum {string} */
            status: "ACTIVE" | "COMPLETED" | "ABANDONED";
            /**
             * @description Toute activité est une source attribuée. `MANUAL_TIMER` en v1 ; les autres arrivent sans changer ce contrat.
             * @enum {string}
             */
            source: "MANUAL_TIMER" | "STRAVA" | "HEALTHKIT";
            /** @enum {string} */
            trust: "DECLARED" | "PROVIDER_VERIFIED";
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            endedAt: string | null;
            durationSeconds: number | null;
        };
        /** @description Pagination par curseur, sur l'identifiant — UUID v7, donc triable, donc chronologique. `nextCursor` à `null` signifie la fin. */
        SessionPage: {
            sessions: components["schemas"]["TrainingSession"][];
            /** Format: uuid */
            nextCursor: string | null;
        };
        /**
         * @description Une contribution au total, entier signé. Un multiplicateur se résout en points
         *     **avant** d'arriver ici : ce qui est écrit est ce que le joueur a reçu, pas la
         *     formule. Les deux dernières sources sont des garde-fous, négatives au crédit.
         */
        XpLine: {
            /** @enum {string} */
            source: "BASE" | "STREAK" | "ITEM" | "SKILL" | "LEAGUE" | "DIMINISHING" | "DAILY_CAP";
            /** @example -55 */
            amount: number;
        };
        /**
         * @description **Le contrat le plus coûteux à casser du produit.** Ce que le joueur reçoit quand il
         *     appuie sur « terminer ».
         *
         *     **L'ordre des champs est l'ordre de l'animation** : le client le joue de haut en
         *     bas — la séance se referme, la barre d'XP se remplit ligne à ligne, le niveau
         *     bascule, le titre tombe, puis le loot et la série. Un champ déplacé change la mise
         *     en scène.
         *
         *     **Un seul aller-retour.** Rien ici ne demande de recharger quoi que ce soit avant de
         *     jouer l'animation — d'où le niveau donné avant *et* après, et les titres déjà
         *     traduits.
         *
         *     `loot`, `streak` et `unlockableNodes` sont **présents et vides** jusqu'aux Lots 6, 5
         *     et 7. Une clé qui apparaîtrait plus tard obligerait un client déjà déployé à la
         *     rendre optionnelle pour toujours.
         */
        RewardSummary: {
            session: components["schemas"]["TrainingSession"];
            xp: {
                /**
                 * @description La somme du `breakdown`, jamais autre chose.
                 * @example 145
                 */
                awarded: number;
                /** @description Dans l'ordre d'affichage. Le client ne le trie pas, il le joue. */
                breakdown: components["schemas"]["XpLine"][];
            };
            level: {
                /** @example 1 */
                before: number;
                /** @example 2 */
                after: number;
                /** @description Les niveaux franchis, dans l'ordre. En gagner plusieurs d'un coup est un cas normal — le client les anime tous. Vide quand rien ne bouge. */
                reached: number[];
                totalXp: number;
                xpIntoLevel: number;
                /** @description Ce qu'il **reste** à gagner. `null` signifie le niveau maximum ; zéro voudrait dire « atteint ». */
                xpToNextLevel: number | null;
                skillPointsGranted: number;
            };
            /** @description Vide le plus souvent — un titre est un événement rare, c'est ce qui en fait un. */
            titlesUnlocked: components["schemas"]["PlayerTitle"][];
            /** @description Lot 6 : toujours vide aujourd'hui. */
            loot: Record<string, never>[];
            /** @description Lot 5 : toujours `null` aujourd'hui. */
            streak: Record<string, never> | null;
            /** @description Lot 7 : toujours vide aujourd'hui. */
            unlockableNodes: Record<string, never>[];
            /** @description L'équilibrage sous lequel ces montants ont été accordés. Le client n'en fait rien ; un rapport de bug, si. */
            rulesetVersion: string;
        };
        /** @description L'état du joueur — l'écran d'accueil de l'app en une requête, servi du seul snapshot. */
        Progression: {
            level: number;
            totalXp: number;
            xpIntoLevel: number;
            /** @description `null` au niveau maximum. */
            xpToNextLevel: number | null;
            /**
             * @description Deux nombres, alors qu'ils valent la même chose aujourd'hui. `earned` est un
             *     cumul de carrière qui ne redescend pas, `available` un solde que les arbres
             *     feront baisser. Les fondre obligerait à renommer — donc à casser le client —
             *     au premier point dépensé.
             */
            skillPoints: {
                earned: number;
                available: number;
            };
            activeTitle: components["schemas"]["PlayerTitle"] | null;
            unlockedTitles: components["schemas"]["PlayerTitle"][];
            rulesetVersion: string;
            /**
             * Format: date-time
             * @description `null` pour un joueur qui n'a encore rien fait.
             */
            lastProgressionAt: string | null;
        };
        /**
         * @description Le catalogue **entier**, traduit et situé. Pas seulement l'acquis : un mur qui ne
         *     montrerait que l'atteint ne donnerait rien à viser.
         */
        TitleBoard: {
            /** @description Redondant avec le tableau — il évite de le parcourir pour savoir quoi cocher, et dit `null` sans ambiguïté. */
            activeTitleId: string | null;
            titles: components["schemas"]["PlayerTitle"][];
        };
        /**
         * @description Une écriture au ledger. **Le ledger est la vérité** ; le niveau et le total en sont
         *     des projections. Rien ne s'efface : une séance invalidée produit une écriture
         *     négative, et les deux restent.
         */
        XpTransaction: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description Ce qui a produit l'écriture — l'identifiant de la séance en v1.
             */
            sourceId: string;
            /** @enum {string} */
            reason: "SESSION_COMPLETED" | "SESSION_INVALIDATED";
            /** @enum {string} */
            discipline: "RUNNING" | "CYCLING" | "SWIMMING" | "STRENGTH" | "MOBILITY" | "CLIMBING";
            /** @description Signé. La somme du `breakdown`, jamais autre chose. */
            amount: number;
            /** @description Signée elle aussi — négative sur une annulation. */
            durationSeconds: number;
            breakdown: components["schemas"]["XpLine"][];
            /** @description Celui du calcul, pas celui d'aujourd'hui. C'est ce qui permet de rééquilibrer sans corrompre l'historique. */
            rulesetVersion: string;
            /** Format: date-time */
            createdAt: string;
        };
        XpHistoryPage: {
            transactions: components["schemas"]["XpTransaction"][];
            /** Format: uuid */
            nextCursor: string | null;
        };
        RefreshTokenRequest: {
            /** @default  */
            refreshToken: string;
        };
        UpdateProfileRequest: {
            /** @default null */
            displayName: string | null;
            /** @default null */
            timezone: string | null;
        };
        RegisterRequest: {
            /** @default  */
            email: string;
            /** @default  */
            password: string;
            /** @default  */
            displayName: string;
            /** @default UTC */
            timezone: string;
        };
        SocialSignInRequest: {
            /** @default  */
            code: string;
            /** @default  */
            redirectUri: string;
            /** @default null */
            codeVerifier: string | null;
            /** @default UTC */
            timezone: string;
        };
        XpHistoryQuery: {
            /**
             * Format: uuid
             * @default null
             */
            cursor: string | null;
            /** @default 20 */
            limit: number;
        };
        SelectTitleRequest: {
            /** @default null */
            titleId: string | null;
        };
        /** @enum {string} */
        SessionStatus: "ACTIVE" | "COMPLETED" | "ABANDONED";
        /** @enum {string} */
        Discipline: "RUNNING" | "CYCLING" | "SWIMMING" | "STRENGTH" | "MOBILITY" | "CLIMBING";
        SessionHistoryQuery: {
            /** @default null */
            status: components["schemas"]["SessionStatus"] | null;
            /** @default null */
            discipline: components["schemas"]["Discipline"] | null;
            /**
             * Format: date-time
             * @default null
             */
            from: string | null;
            /**
             * Format: date-time
             * @default null
             */
            to: string | null;
            /**
             * Format: uuid
             * @default null
             */
            cursor: string | null;
            /** @default 20 */
            limit: number;
        };
        StartSessionRequest: {
            discipline: components["schemas"]["Discipline"];
        };
    };
    responses: {
        /** @description Requête malformée — en-tête d'idempotence absent, corps illisible. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Jeton absent, expiré ou invalide. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description La ressource n'existe pas, **ou n'appartient pas à ce compte**. Les deux cas
         *     rendent la même réponse : répondre « interdit » confirmerait l'existence, et un
         *     identifiant, ça s'essaie en boucle.
         */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description L'état actuel refuse l'opération. Le `type` dit lequel, et les membres supplémentaires disent comment se recaler. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Le corps est bien formé mais son contenu est refusé. */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ValidationProblem"];
            };
        };
    };
    parameters: {
        /**
         * @description Une clé propre à cette tentative, stable au travers des rejeus du client.
         *     Rejouer la même clé sur la même requête rend la réponse d'origine sans rien
         *     réexécuter, et l'en-tête `Idempotent-Replay: true` le signale. La même clé sur
         *     une requête différente est un abus et vaut un 409.
         */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    post_identity_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    /** Format: password */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Identifiants acceptés. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSession"];
                };
            };
            /** @description Identifiants refusés. La réponse ne distingue pas une adresse inconnue d'un mot de passe faux, et le temps de réponse non plus (#39). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    post_identity_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description La famille entière est révoquée — c'est l'appareil qui se déconnecte, pas seulement ce jeton. Rien à rendre. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    get_identity_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Le profil, titre porté et titre visé compris : l'état du joueur en une requête à l'ouverture de l'app. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    patch_identity_me_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Le profil mis à jour. Les champs absents ne sont pas touchés. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    post_identity_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description Une paire neuve. **Le jeton présenté est consommé** : il est à usage unique et rotatif. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSession"];
                };
            };
            /** @description Jeton inconnu, expiré, **ou déjà consommé** (`invalid-refresh-token`). Un rejeu révoque toute la famille : on ne peut pas distinguer le voleur du vrai client qui a été doublé, donc on coupe. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    post_identity_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Le compte est ouvert **et la session aussi** : forcer un login juste après ajouterait un aller-retour sur l'étape la plus fragile du tunnel. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSession"];
                };
            };
            /** @description Adresse déjà prise (`email-already-used`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    post_identity_social_sign_in: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: "google" | "apple";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SocialSignInRequest"];
            };
        };
        responses: {
            /** @description Compte rattaché ou créé. Un compte né ici n'a pas de mot de passe et ne peut pas passer par `/api/auth/login`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSession"];
                };
            };
            /** @description Le fournisseur a refusé le code (`social-sign-in-rejected`). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description L'adresse appartient à un compte existant que le fournisseur ne certifie pas (`email-belongs-to-another-account`) — sans certification, rattacher serait une prise de contrôle en une requête. Ou profil incomplet (`social-profile-incomplete`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    get_progression_state: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description L'état du joueur, servi du seul snapshot — aucune relecture du ledger. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Progression"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    get_progression_history: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Une page du ledger, la plus récente d'abord. C'est la vérité dont le niveau est une projection. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["XpHistoryPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    get_progression_titles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Le catalogue entier, situé pour ce joueur. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TitleBoard"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    put_progression_titles_select: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectTitleRequest"];
            };
        };
        responses: {
            /** @description Le mur des titres, avec le nouveau titre porté. `titleId` à `null` n'en affiche aucun. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TitleBoard"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Titre inconnu du catalogue (`title-unknown`) ou non débloqué par ce joueur (`title-not-unlocked`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    post_training_session_abandon: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Une clé propre à cette tentative, stable au travers des rejeus du client.
                 *     Rejouer la même clé sur la même requête rend la réponse d'origine sans rien
                 *     réexécuter, et l'en-tête `Idempotent-Replay: true` le signale. La même clé sur
                 *     une requête différente est un abus et vaut un 409.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** @description Aucun corps attendu. */
        requestBody?: {
            content: {
                "*/*"?: never;
            };
        };
        responses: {
            /** @description La séance est close et ne rapporte rien. Elle reste dans l'historique. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingSession"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    get_training_session_active: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La séance en cours. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingSession"];
                };
            };
            /** @description Aucune séance en cours — l'état normal du joueur, pas une erreur. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    post_training_session_complete: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Une clé propre à cette tentative, stable au travers des rejeus du client.
                 *     Rejouer la même clé sur la même requête rend la réponse d'origine sans rien
                 *     réexécuter, et l'en-tête `Idempotent-Replay: true` le signale. La même clé sur
                 *     une requête différente est un abus et vaut un 409.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** @description Aucun corps attendu. Le serveur ne lit ni durée ni date de fin : il lit son horloge. */
        requestBody?: {
            content: {
                "*/*"?: never;
            };
        };
        responses: {
            /** @description La séance est close et créditée. Le corps est le `RewardSummary`, à jouer de haut en bas. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RewardSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Séance déjà close (`session-not-active`), sous la durée plancher (`session-too-short`), ou clé d'idempotence en cours (`idempotency-key-in-flight`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    get_training_session_list: {
        parameters: {
            query?: {
                status?: components["schemas"]["SessionStatus"] | null;
                discipline?: components["schemas"]["Discipline"] | null;
                from?: string | null;
                to?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Une page d'historique, du plus récent au plus ancien. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    post_training_session_start: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartSessionRequest"];
            };
        };
        responses: {
            /** @description La séance est ouverte, datée par le serveur. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingSession"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Une séance tourne déjà (`session-already-active`, avec `activeSessionId`), ou le cooldown court encore (`session-cooldown`, avec `remainingSeconds` et `readyAt`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            422: components["responses"]["UnprocessableEntity"];
        };
    };
}
