/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/guilds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_community_guild_found"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/guilds/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_community_guild_show"];
        put?: never;
        post?: never;
        delete: operations["delete_community_guild_dissolve"];
        options?: never;
        head?: never;
        patch: operations["patch_community_guild_rename"];
        trace?: never;
    };
    "/api/guilds/{id}/invite-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_community_invite_code_issue"];
        delete: operations["delete_community_invite_code_revoke"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/guilds/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Le limiteur est **configuré, pas écrit** : la politique et les seuils vivent dans
         *     `config/packages/rate_limiter.yaml`, et l'attribut ne fait que désigner la clé.
         * @description Cette clé est le joueur et non l'IP — une IP mobile change en cours de trajet et se
         *     partage entre colocataires, alors que seul un compte authentifié peut consommer un
         *     code. `args["user"]` est l'argument du contrôleur, disponible parce que l'attribut
         *     est traité sur `kernel.controller_arguments`, après résolution.
         */
        post: operations["post_community_guild_join"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/guilds/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_community_guild_mine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/guilds/mine/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_community_guild_leave"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/guilds/{id}/members/{playerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_community_guild_exclude"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_community_player_show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_identity_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Le jeton d'accès n'est pas requis : la preuve de possession du refresh token
         *     suffit, et c'est justement quand le JWT vient d'expirer qu'on veut pouvoir
         *     se déconnecter proprement.
         */
        post: operations["post_identity_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_identity_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patch_identity_me_update"];
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_identity_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_identity_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/social/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_identity_social_sign_in"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progression": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_progression_state"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progression/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * L'argument `#[MapQueryString]` n'est ni nullable ni pourvu d'un défaut, et c'est
         *     voulu : le résolveur ne construit le DTO sur une query string vide que dans ce
         *     cas-là. Nullable, il faudrait un `?? new XpHistoryQuery()` à la main.
         */
        get: operations["get_progression_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/titles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_progression_titles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/titles/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["put_progression_titles_select"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workouts/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_training_workout_import"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_training_workout_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workouts/sync-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_training_workout_sync_state"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Une erreur, RFC 9457. `type` est l'identifiant stable de la panne ; `title` et
         *     `detail` sont du texte. Certaines erreurs ajoutent leurs propres membres — une
         *     violation de validation donne `violations` — pour que le client se recale au lieu
         *     d'afficher un refus sec.
         */
        ProblemDetails: {
            /**
             * Format: uri
             * @description **L'énumération est exhaustive** : tout ce que le back sait émettre est ici,
             *     pannes de transport comprises. C'est ce qui permet au client d'en faire un
             *     `switch` exhaustif et de laisser son compilateur réclamer un cas quand une
             *     panne s'ajoute — brancher un message sur le statut HTTP à la place ne
             *     marcherait pas, un même statut couvrant des pannes qui n'appellent pas la
             *     même phrase.
             *
             *     `OpenApiContractTest` compare cette liste à ce que le code produit, dans les
             *     deux sens : elle ne peut ni oublier une panne ni en garder une disparue.
             * @enum {string}
             */
            type: "https://grrind.app/problems/bad-request" | "https://grrind.app/problems/not-found" | "https://grrind.app/problems/forbidden" | "https://grrind.app/problems/method-not-allowed" | "https://grrind.app/problems/too-many-requests" | "https://grrind.app/problems/unsupported-media-type" | "https://grrind.app/problems/validation-failed" | "https://grrind.app/problems/internal-error" | "https://grrind.app/problems/idempotency-key-required" | "https://grrind.app/problems/idempotency-key-in-flight" | "https://grrind.app/problems/idempotency-key-reused" | "https://grrind.app/problems/email-already-used" | "https://grrind.app/problems/email-belongs-to-another-account" | "https://grrind.app/problems/invalid-credentials" | "https://grrind.app/problems/access-token-missing" | "https://grrind.app/problems/access-token-expired" | "https://grrind.app/problems/access-token-invalid" | "https://grrind.app/problems/invalid-refresh-token" | "https://grrind.app/problems/social-sign-in-rejected" | "https://grrind.app/problems/social-profile-incomplete" | "https://grrind.app/problems/title-unknown" | "https://grrind.app/problems/title-not-unlocked" | "https://grrind.app/problems/guild-is-full" | "https://grrind.app/problems/player-already-in-a-guild" | "https://grrind.app/problems/guild-not-found" | "https://grrind.app/problems/invite-code-not-usable" | "https://grrind.app/problems/player-is-not-a-member" | "https://grrind.app/problems/founder-cannot-exclude-himself" | "https://grrind.app/problems/player-not-found";
            /** @example Conflict */
            title: string;
            /** @example 409 */
            status: number;
            detail: string;
        } & {
            [key: string]: unknown;
        };
        /** @description Le corps est bien formé mais son contenu est refusé. Chaque violation nomme son champ. */
        ValidationProblem: components["schemas"]["ProblemDetails"] & {
            violations?: {
                /** @example email */
                field: string;
                message: string;
            }[];
        };
        /**
         * @description **La seule forme d'un titre dans toute l'API** — débloqué comme verrouillé, dans le
         *     profil, sur le mur des titres et dans une récompense. Un seul type à décoder, un
         *     seul composant à dessiner.
         *
         *     `unlockedAt` à `null` est ce qui distingue les deux états. `progress` est toujours
         *     renseignée : sur un titre acquis, `current` vaut `target`.
         */
        PlayerTitle: {
            /** @example first_steps */
            id: string;
            /**
             * @description Déjà traduit, dans la langue négociée sur `Accept-Language`.
             * @example First Steps
             */
            name: string;
            /**
             * @description Ce qu'il reste à faire, rédigé.
             * @example Complete your first session
             */
            hint: string;
            unlocked: boolean;
            /** Format: date-time */
            unlockedAt: string | null;
            progress: {
                /** @description Écrêté à `target` — une barre ne dépasse pas. */
                current: number;
                target: number;
                /** @enum {string} */
                unit: "LEVELS" | "XP" | "SESSIONS" | "SECONDS";
            };
        };
        /**
         * @description Le nom seul. **Il n'est pas unique**, et il ne le deviendra pas : on n'entre
         *     dans une guilde que par un code d'invitation, donc rien ne dépend de pouvoir la
         *     désigner par son nom. Deux guildes homonymes sont un cas normal.
         */
        GuildName: {
            /** @example Les Lève-Tôt */
            name: string;
        };
        /**
         * @description Une guilde, vue par l'un de ses membres. Elle **ne produit aucune valeur de
         *     jeu** en v1 : ni XP, ni modificateur, ni loot. Elle réunit des joueurs, c'est
         *     tout.
         */
        Guild: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: date-time */
            createdAt: string;
            /** @example 12 */
            memberCount: number;
            /**
             * @description La capacité vient de l'équilibrage du serveur et voyage avec la
             *     réponse : l'écran affiche « 12 / 30 », et embarquer le dénominateur
             *     dans l'app obligerait à repasser par l'App Store pour le corriger.
             * @example 30
             */
            capacity: number;
            /**
             * @description Le rôle de **l'appelant**, pas une propriété de la guilde. Il sert à
             *     décider quoi dessiner — le bouton « dissoudre » n'existe que pour le
             *     fondateur — jamais à autoriser : le serveur reste seul juge, et
             *     l'action est de toute façon revérifiée.
             * @enum {string}
             */
            role: "FOUNDER" | "MEMBER";
        };
        /**
         * @description Le laissez-passer d'une guilde. Il **remplace l'annuaire au lieu de le
         *     compléter** : aucune recherche de joueur n'existe, et une recherche par adresse
         *     rendrait l'API capable de confirmer qu'une adresse a un compte. Le code se
         *     partage hors de l'app, et seul un joueur déjà inscrit et connecté peut le
         *     consommer.
         */
        GuildInviteCode: {
            /**
             * @description Huit caractères sur un alphabet **amputé de ce qui se confond** : ni
             *     `O` ni `0`, ni `I`, `L` ou `1`. Un code se lit au téléphone et se
             *     recopie d'une capture d'écran.
             * @example K7QM3XPB
             */
            code: string;
            /**
             * Format: date-time
             * @description Une date et non une durée restante : l'écran affiche « valable jusqu'à
             *     demain 18 h », et des secondes se périmeraient dans la réponse
             *     elle-même.
             */
            expiresAt: string;
        };
        /**
         * @description **Aucun identifiant de guilde** : c'est le code qui la désigne, sans quoi il
         *     suffirait d'un UUID pour entrer. Le serveur normalise la casse et les espaces,
         *     donc un code collé depuis un message passe tel quel.
         */
        GuildJoin: {
            /** @example K7QM3XPB */
            code: string;
        };
        /**
         * @description Un joueur **tel que les autres joueurs le voient** — la seule forme sous
         *     laquelle l'API expose quelqu'un d'autre que soi-même. Servie telle quelle par
         *     `GET /api/players/{id}`, et étalée dans chaque membre d'une guilde.
         *
         *     **Ce qui n'y figure pas est la moitié du contrat** : ni adresse, ni fuseau, ni
         *     rôle applicatif. Ce sont des données de compte, pas de profil public — et les
         *     ports qui alimentent cette ressource ne les rendent tout simplement pas.
         */
        Player: {
            /** Format: uuid */
            id: string;
            /**
             * @description **Non unique, et il ne le deviendra pas ici.** Deux membres homonymes
             *     sont un cas normal ; c'est l'`id` qui distingue.
             */
            displayName: string;
            /** Format: date-time */
            registeredAt: string;
            /** @example 12 */
            level: number;
            /** @example 340 */
            xpIntoLevel: number;
            /** @description `null` au niveau maximum : il n'y a plus de suivant, et zéro voudrait dire « atteint ». */
            xpToNextLevel: number | null;
            /**
             * @description Le titre **porté**, `null` si le joueur n'en affiche aucun. Le
             *     *prochain* titre visé n'y est pas : il n'a de sens que sur son propre
             *     profil, et personne n'a à savoir ce qu'un co-équipier est en train de
             *     viser. C'est `GET /api/me` qui le sert.
             */
            title: components["schemas"]["PlayerTitle"] | null;
        };
        /**
         * @description Un membre : le joueur public, plus ce que la guilde sait de lui. Les champs de
         *     `Player` sont **étalés** et non imbriqués — le client dessine une ligne, pas
         *     deux objets, et `GET /api/players/{id}` sert exactement le même bloc.
         */
        GuildMember: components["schemas"]["Player"] & {
            /** @enum {string} */
            role: "FOUNDER" | "MEMBER";
            /** Format: date-time */
            joinedAt: string;
        };
        /**
         * @description La guilde et ses membres d'un bloc — **c'est l'écran**. L'onglet ne s'ouvre
         *     jamais sans les deux, et les séparer coûterait un aller-retour pour un écran
         *     qui n'a rien à afficher entre-temps.
         */
        GuildDetail: components["schemas"]["Guild"] & {
            /**
             * @description **Le fondateur d'abord, puis par date d'entrée croissante.** Un
             *     ordre décidé par le serveur, jamais celui que rend la base : sans
             *     `ORDER BY`, PostgreSQL sert les lignes comme il veut et change
             *     d'avis quand la table grossit. Une liste qui se réordonne toute
             *     seule entre deux ouvertures d'écran est un bug qu'on ne sait pas
             *     reproduire.
             */
            members: components["schemas"]["GuildMember"][];
        };
        /**
         * @description L'enveloppe de `GET /api/guilds/mine`. Elle existe parce que « pas de guilde »
         *     doit être une réponse et non une erreur : c'est la requête d'ouverture de
         *     l'onglet, et un joueur sans guilde est dans un état normal — l'écran l'invite à
         *     en fonder une.
         */
        MyGuild: {
            guild: components["schemas"]["GuildDetail"] | null;
        };
        UserProfile: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            displayName: string;
            /**
             * @description Identifiant IANA. **Le streak et le plafond quotidien se calculent dedans** : c'est un attribut de profil, jamais une déduction.
             * @example Europe/Paris
             */
            timezone: string;
            /** Format: date-time */
            registeredAt: string;
            /** @description Le titre porté, ou `null` si le joueur n'en a débloqué aucun ou n'en affiche aucun. */
            title: components["schemas"]["PlayerTitle"] | null;
            /** @description Le plus proche d'aboutir parmi ceux qui restent. `null` quand il les a tous. */
            nextTitle: components["schemas"]["PlayerTitle"] | null;
        };
        /**
         * @description Deux jetons de nature différente. Le JWT porte l'identité et ne se révoque pas —
         *     d'où sa courte durée. Le refresh token est **à usage unique et rotatif**, groupé par
         *     famille : une famille est un appareil connecté, s'en déconnecter la révoque
         *     entièrement. Rejouer un jeton déjà consommé révoque toute la famille.
         */
        TokenPair: {
            accessToken: string;
            /** @enum {string} */
            tokenType: "Bearer";
            /**
             * @description Secondes de validité du JWT.
             * @example 900
             */
            expiresIn: number;
            refreshToken: string;
            /** Format: date-time */
            refreshTokenExpiresAt: string;
        };
        /** @description Ce que rendent l'inscription, la connexion et le rafraîchissement — le profil et la paire de jetons, en une réponse. */
        AuthSession: {
            user: components["schemas"]["UserProfile"];
            tokens: components["schemas"]["TokenPair"];
        };
        /**
         * @description **La seule forme d'un workout dans toute l'API** — l'historique la sert, le `SyncSummary`
         *     l'embarque telle quelle. Un client décode un seul type.
         *
         *     Une séance **déjà faite** : elle n'a pas d'état, et `endedAt` comme `durationSeconds` ne
         *     sont pas nullables. Un workout arrive terminé ou n'arrive pas.
         *
         *     `durationSeconds` est calculée par le serveur à partir des deux bornes, jamais recopiée
         *     d'un champ envoyé par le client. C'est la durée **réellement mesurée** : au-delà du
         *     plafond, l'XP est calculée sur une durée écrêtée, mais l'historique dit ce qui s'est
         *     passé.
         *
         *     **Les mesures sont nullables, et c'est structurel** : aucun appareil ne fournit tout.
         *     `null` veut dire « non mesuré », jamais zéro — un tour de piste plat a bien un dénivelé
         *     de zéro.
         */
        Workout: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            discipline: "RUNNING" | "WALKING" | "CYCLING" | "SWIMMING" | "STRENGTH" | "HIIT" | "HIKING" | "MOBILITY" | "CLIMBING";
            /**
             * @description L'agrégateur de plateforme qui a rapporté la séance, pas l'appareil qui l'a
             *     mesurée : une montre Garmin arrive en `APPLE_HEALTH` sur iPhone et en
             *     `HEALTH_CONNECT` sur Android.
             * @enum {string}
             */
            source: "APPLE_HEALTH" | "HEALTH_CONNECT";
            /**
             * @description Toujours `PROVIDER_VERIFIED` aujourd'hui : les deux sources sont vérifiées. `DECLARED` reste le plancher de l'échelle, pas une valeur morte.
             * @enum {string}
             */
            trust: "DECLARED" | "PROVIDER_VERIFIED";
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            endedAt: string;
            durationSeconds: number;
            distanceMeters: number | null;
            calories: number | null;
            elevationGainMeters: number | null;
            averageHeartRate: number | null;
            /** @description L'identifiant chez le fournisseur, rendu parce que c'est le client qui l'a envoyé : il peut ainsi rapprocher sa liste HealthKit de ce que le serveur connaît déjà, sans deviner. */
            externalId: string | null;
        };
        /**
         * @description Une page d'historique, **dans l'ordre de la pratique** : `startedAt` décroissant, puis
         *     l'identifiant pour départager deux séances commencées à la même seconde.
         *
         *     `nextCursor` est une **chaîne opaque** — le client la renvoie telle quelle, il n'a rien à
         *     y lire. `null` signifie la fin ; il n'y a pas de total, un défilement infini n'en a aucun
         *     usage.
         */
        WorkoutPage: {
            workouts: components["schemas"]["Workout"][];
            nextCursor: string | null;
        };
        /**
         * @description De quoi demander la bonne fenêtre à HealthKit ou Health Connect.
         *
         *     **Le curseur vient du serveur.** Le client peut garder sa date de dernière
         *     synchronisation en local, et il le fera pour éviter un aller-retour au démarrage — mais
         *     il ne doit pas en *dépendre* : réinstallation, changement d'appareil, second appareil sur
         *     le même compte. Le cache local est une optimisation, pas la vérité.
         *
         *     **La fenêtre est servie et pas codée en dur** : elle doit pouvoir bouger sans publication
         *     sur les stores. Une app qui demanderait trente jours pendant que le serveur en accepte
         *     soixante enverrait moins que ce qu'elle pourrait.
         */
        SyncState: {
            /**
             * Format: date-time
             * @description La fin du workout le plus récent que le serveur ait en base — pas la date du dernier
             *     appel d'import, qui a pu ne rien apporter. Les séances archivées hors fenêtre comptent :
             *     ce qu'on désigne ici est la frontière de ce que le serveur **connaît**, pas de ce qu'il a
             *     payé. `null` sur un compte qui n'a jamais synchronisé.
             */
            lastImportedAt: string | null;
            /**
             * @description Au-delà, une séance est conservée mais ne rapporte pas d'XP. C'est ce qui empêche trois ans d'archives d'amener un joueur au niveau 60 avant sa première course pour Grrind.
             * @example 30
             */
            importWindowDays: number;
        };
        /**
         * @description Ce que la montre a enregistré depuis la dernière synchronisation. **Un lot, pas un
         *     workout** : revenir après dix jours d'absence avec trois séances à créditer est le cas
         *     nominal.
         *
         *     Le client envoie le **type brut du fournisseur**, jamais une `discipline` : la
         *     traduction est serveur, ce qui permet d'ouvrir un sport sans publier sur les stores.
         *     Un type inconnu n'est pas une erreur — la séance est écartée et nommée dans la
         *     réponse.
         *
         *     **La durée n'est pas un champ.** Elle se dérive de `startedAt` et `endedAt`, arbitrée
         *     par le serveur : l'accepter en entrée donnerait au client une prise sur ce qu'il gagne.
         */
        WorkoutImportRequest: {
            workouts: components["schemas"]["ImportedWorkout"][];
        };
        /** @description Une séance candidate. Les mesures sont toutes facultatives, et c'est structurel : aucun appareil ne fournit tout. `null` veut dire « non mesuré », jamais zéro. */
        ImportedWorkout: {
            /** @description `HKWorkout.uuid` côté Apple, `metadata.id` côté Health Connect. Il porte toute la protection contre le double crédit — le renvoyer à l'identique est ce qui rend une resynchronisation inoffensive. */
            externalId: string;
            /** @enum {string} */
            source: "APPLE_HEALTH" | "HEALTH_CONNECT";
            /**
             * @description Le nom de case `HKWorkoutActivityType` côté Apple, la constante `EXERCISE_TYPE_*` côté Health Connect. Envoyé tel quel, sans interprétation.
             * @example traditionalStrengthTraining
             */
            activityType: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            endedAt: string;
            distanceMeters?: number | null;
            calories?: number | null;
            elevationGainMeters?: number | null;
            averageHeartRate?: number | null;
        };
        /**
         * @description **Le contrat le plus coûteux à casser du produit**, dans sa forme multi-workouts. Ce que
         *     le joueur reçoit quand sa montre a fini de parler.
         *
         *     **L'ordre des champs est l'ordre de l'animation**, à deux niveaux : d'abord entre les
         *     workouts — `imported` est chronologique, celui du crédit — puis à l'intérieur de chacun.
         *
         *     **Rien n'est tronqué.** Au-delà d'une vingtaine de workouts, tout jouer prend plusieurs
         *     minutes : c'est une décision de mise en scène, et elle appartient au client. Le serveur
         *     envoie tout, le client décide de ce qu'il joue.
         */
        SyncSummary: {
            /**
             * Format: date-time
             * @description L'horloge du serveur, et le seul instant de ce payload qui ne vienne pas d'un fournisseur. Sert de repère de dernière synchronisation réussie.
             */
            syncedAt: string;
            /**
             * @description Un `RewardSummary` par workout crédité, dans l'ordre chronologique. **C'est
             *     exactement l'objet que le client sait déjà jouer**, palier de départ compris : la
             *     barre part du bon endroit pour *chacun*, et l'enchaînement est continu sans un seul
             *     recalcul côté client.
             */
            imported: components["schemas"]["RewardSummary"][];
            /**
             * @description Les séances qui n'ont **rien rapporté**, chacune **nommée** et non comptée : le client
             *     doit pouvoir dire « le curling n'est pas encore un sport chez nous » plutôt que « 1
             *     séance ignorée ».
             *
             *     Écarté ne veut pas toujours dire absent. `OUT_OF_WINDOW` écarte le *crédit*, pas la
             *     séance : elle est bien en base et apparaîtra dans l'historique.
             */
            skipped: {
                externalId: string;
                activityType: string;
                /**
                 * @description `ALREADY_IMPORTED` : déjà en base sous le même couple (source, identifiant). Banal
                 *     et attendu — c'est ce que rend un client qui a perdu son curseur.
                 *
                 *     `UNSUPPORTED_ACTIVITY` : aucune discipline ne correspond. Rien n'est écrit, donc
                 *     rien n'est définitif — le jour où le sport entre dans la table serveur, la même
                 *     séance renvoyée est créditée.
                 *
                 *     `OUT_OF_WINDOW` : trop ancienne pour rapporter de l'XP, mais **conservée**. Le
                 *     joueur retrouve son passé sans le monnayer, et le premier import devient un moment
                 *     de produit au lieu d'un mur.
                 *
                 *     `OVERLAPS` : une autre séance couvre déjà ce créneau. Ce ne sont pas deux
                 *     entraînements, c'est le même vu par deux applications — beaucoup de gens ont Apple
                 *     Exercice *et* Strava sans le savoir. C'est l'enregistrement le plus complet qui
                 *     gagne, sauf si l'autre est déjà en base.
                 *
                 *     `TOO_SHORT` : sous le plancher de durée. Un faux départ sur la montre n'est pas une
                 *     séance, et rien n'est écrit.
                 * @enum {string}
                 */
                reason: "ALREADY_IMPORTED" | "UNSUPPORTED_ACTIVITY" | "OUT_OF_WINDOW" | "OVERLAPS" | "TOO_SHORT";
            }[];
            /**
             * @description Le raccourci de l'écran de résumé — « +847 XP · niveau 10 → 15 » — et ce que voit le
             *     joueur qui saute l'animation.
             *
             *     **C'est un raccourci, jamais une source** : il est entièrement dérivé d'`imported`,
             *     qui dit déjà tout. Deux vérités finissent toujours par diverger.
             *
             *     `null` quand rien n'a été crédité : il n'y a pas d'état d'arrivée quand rien n'est
             *     arrivé, et « niveau 0 → 0 » mentirait à un joueur de niveau 12.
             */
            totals: components["schemas"]["SyncTotals"] | null;
            /** @description L'équilibrage sous lequel la synchronisation a été calculée. Affiché dans un rapport de bug : c'est ce qui rend une capture d'écran exploitable. */
            rulesetVersion: string;
        };
        SyncTotals: {
            /** @example 10 */
            levelBefore: number;
            /** @example 15 */
            levelAfter: number;
            xpBefore: number;
            xpAfter: number;
            /** @description La somme des montants accordés, écarts non compris — un workout écarté n'a rien rapporté. */
            xpAwarded: number;
            /** @description Le nombre de workouts **crédités**, donc la longueur d'`imported`. */
            workoutCount: number;
        };
        /**
         * @description Une contribution au total, entier signé. Un multiplicateur se résout en points
         *     **avant** d'arriver ici : ce qui est écrit est ce que le joueur a reçu, pas la
         *     formule. Les deux dernières sources sont des garde-fous, négatives au crédit.
         *
         *     **Une ligne à zéro n'existe pas.** Une métrique non mesurée, un bonus trop petit
         *     pour peser, un garde-fou qui n'a rien repris : rien de tout ça n'occupe une ligne
         *     d'animation. Le client peut donc jouer chaque ligne sans la tester.
         */
        XpLine: {
            /**
             * @description `BASE` est le temps — une minute vaut un point. `DISTANCE` et `ELEVATION`
             *     sont ce que le terrain ajoute, et n'apparaissent que sur les disciplines où
             *     une montre les mesure de façon fiable. Les quatre suivantes sont les
             *     contributeurs de modificateurs ; les deux dernières, les garde-fous.
             * @enum {string}
             */
            source: "BASE" | "DISTANCE" | "ELEVATION" | "STREAK" | "ITEM" | "SKILL" | "LEAGUE" | "DIMINISHING" | "DAILY_CAP";
            /** @example -55 */
            amount: number;
        };
        /**
         * @description Ce que le joueur reçoit pour **un** workout crédité. Un `SyncSummary` en contient
         *     autant qu'il y a eu de séances, dans l'ordre chronologique.
         *
         *     **L'ordre des champs est l'ordre de l'animation** : le client le joue de haut en
         *     bas — la séance se referme, la barre d'XP se remplit ligne à ligne, le niveau
         *     bascule, le titre tombe, puis le loot et la série. Un champ déplacé change la mise
         *     en scène.
         *
         *     **Un seul aller-retour.** Rien ici ne demande de recharger quoi que ce soit avant de
         *     jouer l'animation — d'où le palier donné avant *et* après, et les titres déjà
         *     traduits.
         *
         *     `loot`, `streak` et `unlockableNodes` sont **présents et vides** jusqu'aux Lots 6, 5
         *     et 7. Une clé qui apparaîtrait plus tard obligerait un client déjà déployé à la
         *     rendre optionnelle pour toujours.
         */
        RewardSummary: {
            session: components["schemas"]["Workout"];
            xp: {
                /**
                 * @description La somme du `breakdown`, jamais autre chose.
                 * @example 145
                 */
                awarded: number;
                /** @description Dans l'ordre d'affichage. Le client ne le trie pas, il le joue. */
                breakdown: components["schemas"]["XpLine"][];
            };
            level: {
                /** @example 1 */
                before: number;
                /**
                 * @description Où en était la barre avant la séance. Le client l'y place, **puis** la remplit.
                 * @example 30
                 */
                xpIntoLevelBefore: number;
                /**
                 * @description Avec le précédent, la largeur du palier de départ. Elle ne se redéduit pas du reste dès que plusieurs niveaux sont franchis, et sans elle la barre repart de zéro pour un joueur qui n'y était pas. `null` au niveau maximum.
                 * @example 70
                 */
                xpToNextLevelBefore: number | null;
                /** @example 2 */
                after: number;
                /** @description Les niveaux franchis, dans l'ordre. En gagner plusieurs d'un coup est un cas normal — le client les anime tous. Vide quand rien ne bouge. */
                reached: number[];
                totalXp: number;
                xpIntoLevel: number;
                /** @description Ce qu'il **reste** à gagner. `null` signifie le niveau maximum ; zéro voudrait dire « atteint ». */
                xpToNextLevel: number | null;
                skillPointsGranted: number;
            };
            /** @description Vide le plus souvent — un titre est un événement rare, c'est ce qui en fait un. */
            titlesUnlocked: components["schemas"]["PlayerTitle"][];
            /** @description Lot 6 : toujours vide aujourd'hui. */
            loot: Record<string, never>[];
            /** @description Lot 5 : toujours `null` aujourd'hui. */
            streak: Record<string, never> | null;
            /** @description Lot 7 : toujours vide aujourd'hui. */
            unlockableNodes: Record<string, never>[];
            /** @description L'équilibrage sous lequel ces montants ont été accordés. Le client n'en fait rien ; un rapport de bug, si. */
            rulesetVersion: string;
        };
        /** @description L'état du joueur — l'écran d'accueil de l'app en une requête, servi du seul snapshot. */
        Progression: {
            level: number;
            totalXp: number;
            xpIntoLevel: number;
            /** @description `null` au niveau maximum. */
            xpToNextLevel: number | null;
            /**
             * @description Deux nombres, alors qu'ils valent la même chose aujourd'hui. `earned` est un
             *     cumul de carrière qui ne redescend pas, `available` un solde que les arbres
             *     feront baisser. Les fondre obligerait à renommer — donc à casser le client —
             *     au premier point dépensé.
             */
            skillPoints: {
                earned: number;
                available: number;
            };
            activeTitle: components["schemas"]["PlayerTitle"] | null;
            unlockedTitles: components["schemas"]["PlayerTitle"][];
            rulesetVersion: string;
            /**
             * Format: date-time
             * @description `null` pour un joueur qui n'a encore rien fait.
             */
            lastProgressionAt: string | null;
        };
        /**
         * @description Le catalogue **entier**, traduit et situé. Pas seulement l'acquis : un mur qui ne
         *     montrerait que l'atteint ne donnerait rien à viser.
         */
        TitleBoard: {
            /** @description Redondant avec le tableau — il évite de le parcourir pour savoir quoi cocher, et dit `null` sans ambiguïté. */
            activeTitleId: string | null;
            titles: components["schemas"]["PlayerTitle"][];
        };
        /**
         * @description Une écriture au ledger. **Le ledger est la vérité** ; le niveau et le total en sont
         *     des projections. Rien ne s'efface : une séance invalidée produit une écriture
         *     négative, et les deux restent.
         */
        XpTransaction: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description Ce qui a produit l'écriture — l'identifiant du workout.
             */
            sourceId: string;
            /** @enum {string} */
            reason: "SESSION_COMPLETED" | "SESSION_INVALIDATED";
            /** @enum {string} */
            discipline: "RUNNING" | "WALKING" | "CYCLING" | "SWIMMING" | "STRENGTH" | "HIIT" | "HIKING" | "MOBILITY" | "CLIMBING";
            /** @description Signé. La somme du `breakdown`, jamais autre chose. */
            amount: number;
            /** @description Signée elle aussi — négative sur une annulation. */
            durationSeconds: number;
            breakdown: components["schemas"]["XpLine"][];
            /** @description Celui du calcul, pas celui d'aujourd'hui. C'est ce qui permet de rééquilibrer sans corrompre l'historique. */
            rulesetVersion: string;
            /**
             * Format: date-time
             * @description **L'instant du sport, pas celui de l'écriture.** Un workout de mardi importé
             *     vendredi est daté de mardi : c'est ce qui range l'écriture dans la bonne journée,
             *     pour le plafond quotidien comme pour l'affichage. L'instant de l'écriture, lui,
             *     est encodé dans l'`id` — c'est un UUID v7.
             */
            occurredAt: string;
        };
        /** @description Même pagination qu'à `GET /api/workouts`, curseur opaque compris : deux paginations qui divergeraient coûteraient deux implémentations côté client. L'ordre est celui du sport — `occurredAt` décroissant, puis l'identifiant pour départager. */
        XpHistoryPage: {
            transactions: components["schemas"]["XpTransaction"][];
            nextCursor: string | null;
        };
        FoundGuildRequest: {
            /** @default  */
            name: string;
        };
        RenameGuildRequest: {
            /** @default  */
            name: string;
        };
        JoinGuildRequest: {
            /** @default  */
            code: string;
        };
        RefreshTokenRequest: {
            /** @default  */
            refreshToken: string;
        };
        UpdateProfileRequest: {
            /** @default null */
            displayName: string | null;
            /** @default null */
            timezone: string | null;
        };
        RegisterRequest: {
            /** @default  */
            email: string;
            /** @default  */
            password: string;
            /** @default  */
            displayName: string;
            /** @default UTC */
            timezone: string;
        };
        SocialSignInRequest: {
            /** @default  */
            code: string;
            /** @default  */
            redirectUri: string;
            /** @default null */
            codeVerifier: string | null;
            /** @default UTC */
            timezone: string;
        };
        XpHistoryQuery: {
            /** @default null */
            cursor: string | null;
            /** @default 20 */
            limit: number;
        };
        SelectTitleRequest: {
            /** @default null */
            titleId: string | null;
        };
        /** @enum {string} */
        WorkoutSource: "APPLE_HEALTH" | "HEALTH_CONNECT";
        ImportedWorkoutRequest: {
            /** @default  */
            externalId: string;
            /** @default null */
            source: components["schemas"]["WorkoutSource"] | null;
            /** @default  */
            activityType: string;
            /**
             * Format: date-time
             * @default null
             */
            startedAt: string | null;
            /**
             * Format: date-time
             * @default null
             */
            endedAt: string | null;
            /** @default null */
            distanceMeters: number | null;
            /** @default null */
            calories: number | null;
            /** @default null */
            elevationGainMeters: number | null;
            /** @default null */
            averageHeartRate: number | null;
        };
        ImportWorkoutsRequest: {
            /** @default [] */
            workouts: components["schemas"]["ImportedWorkoutRequest"][];
        };
        /** @enum {string} */
        Discipline: "RUNNING" | "WALKING" | "CYCLING" | "SWIMMING" | "STRENGTH" | "HIIT" | "HIKING" | "MOBILITY" | "CLIMBING";
        WorkoutHistoryQuery: {
            /** @default null */
            discipline: components["schemas"]["Discipline"] | null;
            /**
             * Format: date-time
             * @default null
             */
            from: string | null;
            /**
             * Format: date-time
             * @default null
             */
            to: string | null;
            /** @default null */
            cursor: string | null;
            /** @default 20 */
            limit: number;
        };
    };
    responses: {
        /** @description Requête malformée — en-tête d'idempotence absent, corps illisible. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Le jeton d'accès n'a pas fait son travail, et le `type` dit lequel des trois cas
         *     c'est — `access-token-missing`, `access-token-expired` ou `access-token-invalid`.
         *     La distinction est le tout : **expiré** dit de rafraîchir et de rejouer la requête,
         *     **invalide** et **absent** disent de renvoyer le joueur sur l'écran de connexion.
         */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description La ressource n'existe pas, **ou n'appartient pas à ce compte**. Les deux cas
         *     rendent la même réponse : répondre « interdit » confirmerait l'existence, et un
         *     identifiant, ça s'essaie en boucle.
         */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description L'état actuel refuse l'opération. Le `type` dit lequel, et les membres supplémentaires disent comment se recaler. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description L'appelant est bien identifié, la ressource existe, et il n'a pas le droit
         *     demandé. **C'est ce qui distingue ce statut du 404** : un 403 ne se rend qu'à
         *     quelqu'un qui savait déjà que la ressource existe — un membre de la guilde qui
         *     n'en est pas le fondateur. À un non-membre, l'API répond 404, sans quoi elle
         *     dirait quels UUID désignent une guilde.
         */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Trop d'essais. L'en-tête `Retry-After` dit combien de secondes attendre, et le
         *     client doit l'honorer plutôt que de réessayer en boucle. Aujourd'hui seul
         *     `POST /api/guilds/join` est limité : un code d'invitation est court par
         *     nécessité — il se dicte à voix haute — et c'est ce plafond qui rend le tirage au
         *     hasard sans issue.
         */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Le corps est bien formé mais son contenu est refusé. */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ValidationProblem"];
            };
        };
    };
    parameters: {
        /**
         * @description Une clé propre à cette tentative, stable au travers des rejeus du client.
         *     Rejouer la même clé sur la même requête rend la réponse d'origine sans rien
         *     réexécuter, et l'en-tête `Idempotent-Replay: true` le signale. La même clé sur
         *     une requête différente est un abus et vaut un 409.
         */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    post_community_guild_found: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuildName"];
            };
        };
        responses: {
            /** @description La guilde est fondée et l'appelant en est le fondateur : les deux dans le même geste. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Guild"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Le joueur appartient déjà à une guilde (`player-already-in-a-guild`). Il doit la quitter avant d'en fonder une autre. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    get_community_guild_show: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La même charge utile que `/api/guilds/mine`, sans l'enveloppe : ici la guilde existe forcément, puisqu'un non-membre reçoit 404. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuildDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    delete_community_guild_dissolve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La guilde et toutes ses adhésions sont parties dans la même transaction. Ses membres sont libres d'en fonder ou d'en rejoindre une autre. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    patch_community_guild_rename: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuildName"];
            };
        };
        responses: {
            /** @description La guilde renommée. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Guild"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    post_community_invite_code_issue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Le nouveau code. **Il révoque le précédent** : une guilde n'a jamais deux codes vivants, et régénérer est le geste par lequel on coupe un code qui a trop circulé. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuildInviteCode"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    delete_community_invite_code_revoke: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plus aucun code ne mène à cette guilde. Révoquer alors qu'il n'y avait rien à révoquer rend le même 204 : l'état visé est atteint. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    post_community_guild_join: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuildJoin"];
            };
        };
        responses: {
            /** @description Le joueur est entré. La guilde est rendue en entier, pour que l'écran s'affiche sans second appel. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Guild"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Le code ne mène à rien : **inconnu, expiré ou révoqué, indistinctement** (`invite-code-not-usable`). Les distinguer dirait quels codes existent. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Le joueur appartient déjà à une guilde (`player-already-in-a-guild`), ou celle-ci est complète (`guild-is-full`, qui porte sa `capacity`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    get_community_guild_mine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La guilde du joueur et ses membres, ou `{"guild": null}` s'il n'en a pas. **Pas d'erreur dans ce second cas** : ouvrir l'onglet quand on n'a pas de guilde est une situation normale, pas une panne, et c'est l'écran qui invite à en fonder une. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyGuild"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    post_community_guild_leave: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Le joueur est sorti. Trois issues invisibles pour lui, et toutes dans la même transaction :
             *     il s'en va simplement ; il était fondateur et la guilde passe **au membre le plus ancien** ;
             *     il était le dernier et la guilde est dissoute, code d'invitation compris.
             */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            /** @description Le joueur n'a pas de guilde à quitter (`guild-not-found`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    delete_community_guild_exclude: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                playerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Le membre est sorti. **Il peut revenir avec un code valide** : il n'y a pas de liste
             *     noire en v1, et le recours du fondateur est de révoquer le code — ce qui referme la
             *     guilde pour tout le monde.
             */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description La guilde est invisible à l'appelant (`guild-not-found`), ou le joueur visé n'en est pas membre (`player-is-not-a-member`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Le fondateur a tenté de s'exclure lui-même (`founder-cannot-exclude-himself`). Il doit passer par `POST /api/guilds/mine/leave`, qui sait gérer la succession. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    get_community_player_show: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Le profil public. **Exactement le bloc servi dans la liste des membres** : mêmes ports, même ressource, donc un seul type à décoder côté client. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Player"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /**
             * @description Le joueur n'existe pas, **ou n'est ni soi-même ni un co-équipier** (`player-not-found`).
             *     Les deux cas rendent la même réponse, et **jamais 403** : un 403 confirmerait qu'un
             *     compte porte cet UUID, et les UUID v7 encodent leur instant de création — l'API
             *     deviendrait un moyen d'énumérer les comptes ouverts un jour donné.
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    post_identity_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    /** Format: password */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Identifiants acceptés. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSession"];
                };
            };
            /** @description Identifiants refusés (`invalid-credentials`). La réponse ne distingue pas une adresse inconnue d'un mot de passe faux, et le temps de réponse non plus (#39) — c'est aussi ce que reçoit un compte né d'un social sign-in, qui n'a pas de mot de passe. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    post_identity_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description La famille entière est révoquée — c'est l'appareil qui se déconnecte, pas seulement ce jeton. Rien à rendre. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    get_identity_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Le profil, titre porté et titre visé compris : l'état du joueur en une requête à l'ouverture de l'app. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    patch_identity_me_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Le profil mis à jour. Les champs absents ne sont pas touchés. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    post_identity_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description Une paire neuve. **Le jeton présenté est consommé** : il est à usage unique et rotatif. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSession"];
                };
            };
            /** @description Jeton inconnu, expiré, **ou déjà consommé** (`invalid-refresh-token`). Un rejeu révoque toute la famille : on ne peut pas distinguer le voleur du vrai client qui a été doublé, donc on coupe. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    post_identity_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Le compte est ouvert **et la session aussi** : forcer un login juste après ajouterait un aller-retour sur l'étape la plus fragile du tunnel. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSession"];
                };
            };
            /** @description Adresse déjà prise (`email-already-used`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    post_identity_social_sign_in: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: "google" | "apple";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SocialSignInRequest"];
            };
        };
        responses: {
            /** @description Compte rattaché ou créé. Un compte né ici n'a pas de mot de passe et ne peut pas passer par `/api/auth/login`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSession"];
                };
            };
            /** @description Le fournisseur a refusé le code (`social-sign-in-rejected`). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description L'adresse appartient à un compte existant que le fournisseur ne certifie pas (`email-belongs-to-another-account`) — sans certification, rattacher serait une prise de contrôle en une requête. Ou profil incomplet (`social-profile-incomplete`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    get_progression_state: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description L'état du joueur, servi du seul snapshot — aucune relecture du ledger. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Progression"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    get_progression_history: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Une page du ledger, la plus récente d'abord. C'est la vérité dont le niveau est une projection. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["XpHistoryPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    get_progression_titles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Le catalogue entier, situé pour ce joueur. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TitleBoard"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    put_progression_titles_select: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectTitleRequest"];
            };
        };
        responses: {
            /** @description Le mur des titres, avec le nouveau titre porté. `titleId` à `null` n'en affiche aucun. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TitleBoard"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Titre inconnu du catalogue (`title-unknown`) ou non débloqué par ce joueur (`title-not-unlocked`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    post_training_workout_import: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Une clé propre à cette tentative, stable au travers des rejeus du client.
                 *     Rejouer la même clé sur la même requête rend la réponse d'origine sans rien
                 *     réexécuter, et l'en-tête `Idempotent-Replay: true` le signale. La même clé sur
                 *     une requête différente est un abus et vaut un 409.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutImportRequest"];
            };
        };
        responses: {
            /** @description La synchronisation, prête à être jouée. Un import où tout est écarté reste un succès. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    get_training_workout_list: {
        parameters: {
            query?: {
                discipline?: components["schemas"]["Discipline"] | null;
                from?: string | null;
                to?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Une page d'historique, du plus récent au plus ancien. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    get_training_workout_sync_state: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description De quoi demander la bonne fenêtre au fournisseur santé. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncState"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
